# Generated by Django 3.0.7 on 2020-06-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_author_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['user'], 'verbose_name': 'коментарий', 'verbose_name_plural': 'коментарии'},
        ),
    ]
