# Generated by Django 3.0.7 on 2020-06-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_auto_20200620_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publication_date'], 'verbose_name': 'артикл', 'verbose_name_plural': 'артиклы'},
        ),
    ]
