# Generated by Django 3.0.7 on 2020-06-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0025_auto_20200623_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='tag',
        ),
    ]
